name = "amc10"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "amc10"
database_id = "31209681-39cf-48af-8d7c-db672ebe9a94"
